In [1]:
def weird_not(n):

  if n % 2 != 0: # jika n ganjil
    return "Weird"
  elif 2 <= n <= 5: # Jika n genap rentang 2 -5
    return "Not Weird"
  elif 6 <= n <= 20: # Jika n genap rentang 6 - 20
    return "Weird"
  else:
    return "Not Weird"

In [2]:
  #Input bilangan
  n = int(input().strip())

  # Panggil fungsi dan cetak hasilnya
  print(weird_not(n))


Not Weird


In [3]:
def tambah_kurang_kali(a,b):
  print("Hasil penjumlahan a + b :", a + b)
  print("Hasilpengurangan a - b  :", a - b)
  print("Hasil perkalian a * b   :", a * b)

In [4]:
# Input bilangan
a = int(input("Input nilai a: "))
b = int(input("Input nilai b: "))

# Panggil fungsi
print(tambah_kurang_kali(a,b))

Hasil penjumlahan a + b : 9
Hasilpengurangan a - b  : -3
Hasil perkalian a * b   : 18
None


In [5]:
def bulat_float(a,b):
  print("Hasil pembagian bilangan bulat a dan b   :", a//b)
  print("Hasil pembagian bilangan pecahan a dan b :", a/b)

In [6]:
a = int(input("Input nilai a: "))
b = int(input("Input nilai b: "))

# Panggil fungsi
print(bulat_float(a,b))

Hasil pembagian bilangan bulat a dan b   : 1
Hasil pembagian bilangan pecahan a dan b : 1.6
None


In [7]:
n = int(input("Input sebuah nilai: "))
for i in range(n):
  print(i**2)

0
1
4
9


In [8]:
def is_leap(year):
  leap = False
  if year % 4 == 0:
    leap = True
  elif year % 100 == 0:
    leap = False
  elif year % 400 == 0:
    leap = True
  return leap    

In [9]:
year = int(input("Input sebuah tahun: "))
print(is_leap(year))

False


In [10]:
n = int(input("Input sebuah nilai: "))
for i in range(n):
  print(i+1, end="")

123

In [22]:
import numpy as np

# Membaca ukuran matriks
N = int(input("Masukkan ukuran matrix: "))

# Membaca matriks A
A = []
for _ in range(N) :
    row = list(map(int, input().split()))
    A.append(row)

# Membaca matriks B
B = []
for _ in range(N):
    row = list(map(int, input().split()))
    B.append(row)

# Mengonversi A dan B menjadi array numpy
A = np.array(A)
B = np.array(B)

# Pastikan kedua matriks memiliki ukuran yang sama
if A.shape != B.shape:
    raise ValueError("Matriks A dan B harus memiliki ukuran yang sama.")

# Menghitung hasil kali matriks
result = np.dot(A, B)

# Mencetak hasil
print(result)

[[ 7 10]
 [15 22]]


In [25]:
# Tugas 
# Anda diberikan dua buah array:  A dan B .
# Tugas Anda adalah menghitung hasil kali dalam dan hasil kali luarnya. 

# Format Masukan
# Baris pertama berisi elemen-elemen array A yang dipisahkan spasi.
# Baris kedua berisi elemen-elemen array B yang dipisahkan spasi. 

# Format Keluaran
# Pertama, cetak hasil kali dalam.
# Kedua, cetak hasil kali luar.

# Contoh Masukan
# 0 1
# 2 3

# Contoh Keluaran
# 3
# [[0 0]
#  [2 3]]

import numpy as np
# Mambaca array A
A = np.array(list(map(int, input().split())))

# Mambaca array B
B = np.array(list(map(int, input().split())))

# Menghitung hasil kali dalam
dot_product = np.dot(A, B)

# Menghitung hasil kali luar
cross_product = np.outer(A, B)

print(dot_product)
print(cross_product)



3
[[0 0]
 [2 3]]
